# Jekyll GH-pages Digital Collection Generator

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build

# Site settings
title: Malcolm M. Renfrew Interdisciplinary Colloquium Web Archive
description: Preserving access to past MRIC web content.
keywords: university of idaho, Malcolm M. Renfrew Interdisciplinary Colloquium, digital collections, web archive
owner: University of Idaho Library
email: ewilliamson@uidaho.edu

# url variables
url: https://www.lib.uidaho.edu
baseurl: /digital/mric
liburl: https://www.lib.uidaho.edu
digurl: https://www.lib.uidaho.edu/digital
repourl: https://digital.lib.uidaho.edu

# page gen settings https://github.com/avillafiorita/jekyll-datapage_gen
page_gen:
  - data: 'mric'
    template: 'letter'
    name: 'name'
    dir: 'archive'
    extension: 'html'
